# Deployment
deployment:
  enabled: true
  name: react-app-sta
  namespace: default
  replicas: 3
  appName: react-app-sta
  role: frontend
  containerName: react-app-sta
  imageRepository: lukondefmwila/sita-react
  imageTag: 0.1.2
  port: 80
# Service
service:
  enabled: true
  name: react-app-sta-svc
  namespace: default
  appName: react-app-sta
  type: LoadBalancer
  servicePort: 80
  targetPort: 80
# Ingress
ingress:
  enabled: false
  name: react-app-sta
  namespace: default
  host: lukemwila.com
  path: "/"
  serviceName: react-app-sta-svc
  servicePort: 80
